name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install pypa/build
        run: |
          pip install pipenv
          pipenv install -e .
          pipenv sync --dev

      - name: Build a binary wheel and a source tarball
        run: make build

      - name: Publish distribution to Test PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
          TWINE_USERNAME: __token__
        run: make distribute-test
